import Golf6 from "../images/cars-big/golf6-box.png";
import AudiA1 from "../images/cars-big/audi-box.png";
import Toyota from "../images/cars-big/toyota-box.png";
import Bmw320 from "../images/cars-big/bmw-box.png";
import Benz from "../images/cars-big/benz-box.png";
import Passat from "../images/cars-big/passat-box.png";

export const CAR_MODEL = [
  {
    id: 1,
    name: "Golf 6",
    price: "37",
    img: Golf6,
    model: "Golf 6",
    mark: "Volkswagen",
    year: "2008",
    doors: "4/5",
    air: "Yes",
    transmission: "Manual",
    fuel: "Diesel",
  },
  ,
  {
    id: 2,
    name: "Audi A1 S-Line",
    price: "45",
    img: AudiA1,
    model: "Audi",
    mark: "A1",
    year: "2012",
    doors: "4/5",
    air: "Yes",
    transmission: "Manual",
    fuel: "Gasoline",
  },
  ,
  {
    id: 3,
    name: "Toyota Camry",
    price: "30",
    img: Toyota,
    model: "Camry",
    mark: "Toyota",
    year: "2006",
    doors: "4/5",
    air: "Yes",
    transmission: "Automatic",
    fuel: "Hybrid",
  },
  ,
  {
    id: 4,
    name: "BMW 320 ModernLine",
    price: "35",
    img: Bmw320,
    model: "BMW",
    mark: "BMW",
    year: "2012",
    doors: "4/5",
    air: "Yes",
    transmission: "Manual",
    fuel: "Diesel",
  },
  ,
  {
    id: 5,
    name: "Mercedes-Benz GLK",
    price: "50",
    img: Benz,
    model: "Benz GLK",
    mark: "Mercedes",
    year: "2006",
    doors: "4/5",
    air: "Yes",
    transmission: "Manual",
    fuel: "Diesel",
  },
  ,
  {
    id: 6,
    name: "VW Passat CC",
    price: "25",
    img: Passat,
    model: "Passat CC",
    mark: "Volkswagen",
    year: "2008",
    doors: "4/5",
    air: "Yes",
    transmission: "Automatic",
    fuel: "Gasoline",
  },
  ,
];
